//=====================================
// Analytical Queries, Result Cache, Cloning
//=====================================
USE ROLE      SYSADMIN;
USE WAREHOUSE ANALYTICS_WH;
USE DATABASE  CITIBIKE;
USE SCHEMA    CITIBIKE.PUBLIC;

SELECT * FROM CITIBIKE.PUBLIC.TRIPS LIMIT 20;

SELECT 
  DATE_TRUNC('hour', STARTTIME) AS DATE,
  COUNT(*)                      AS NUM_TRIPS,
  AVG(TRIPDURATION)/60          AS AVG_DURATION_IN_MINUTES, 
  AVG(
    HAVERSINE(
      START_STATION_LATITUDE, 
      START_STATION_LONGITUDE, 
      END_STATION_LATITUDE, 
      END_STATION_LONGITUDE
    )
  )                             AS AVG_DISTANCE_IN_KILOMETERS 
FROM 
  CITIBIKE.PUBLIC.TRIPS
GROUP BY 
  DATE 
ORDER BY 
  DATE;

SELECT 
  DATE_TRUNC('hour', STARTTIME) AS DATE,
  COUNT(*)                      AS NUM_TRIPS,
  AVG(TRIPDURATION)/60          AS AVG_DURATION_IN_MINUTES, 
  AVG(
    HAVERSINE(
      START_STATION_LATITUDE, 
      START_STATION_LONGITUDE, 
      END_STATION_LATITUDE, 
      END_STATION_LONGITUDE
    )
  )                             AS AVG_DISTANCE_IN_KILOMETERS 
FROM 
  CITIBIKE.PUBLIC.TRIPS
GROUP BY 
  DATE 
ORDER BY 
  DATE;

SELECT
  DAYNAME(STARTTIME) AS WEEKDAY,
  COUNT(*) AS NUM_TRIPS
FROM 
  CITIBIKE.PUBLIC.TRIPS
GROUP BY 
  WEEKDAY 
ORDER BY 
  NUM_TRIPS DESC;
